### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by ra002890** [srujithm/react-advanced-gauge-chart#2]
Hello everybory. First of all I woud like to congrats by the good work!
But, is this project still active? Or should/could I create a fork and publish the npm module?
I have created a pull request, that I need to be published to support my enhancements to sammwise that uses this lib. Could you take a look on it? It is mainly about libs bump and changes to transform tha package into a Nextjs compatible module.

**Comment by srujithm** [comment]
Hi @ra002890, First of all, Thank you for looking into the project and contributing changes. This particular change will be very helpful for other developers as well. But for now I am closing this issue as the project is still active and I know couple of orgs using this. I have reviewed your change and it looks good except for a very minor script change. If you could address that, I can go ahead and merge the change.
